# Generated by Django 3.2.5 on 2022-05-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filter_tags',
            field=models.CharField(default='NONE', max_length=100),
            preserve_default=False,
        ),
    ]
